name: Public Invoke-Something

on:
  push:
    paths:
      - 'InkoveSomething/**'
    branches: [ master ]  
  workflow_dispatch:
    

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Publish to nuget
      run: Publish-Module -Path "./InvokeSomething" -NuGetApiKey ${{ secrets.NUGET_API_KEY }} -ReleaseNotes ${{github.event.head_commit.message}} -Repository "Invoke-Something" -ProjectUri "https://github.com/ydinkov/CmdletCarnival" -IconUri "https://raw.githubusercontent.com/ydinkov/CmdletCarnaval/master/InvokeSomething/logo.png" -LicenseUri "https://raw.githubusercontent.com/ydinkov/CmdletCarnaval/master/LICENSE.md"
      shell: powershell
